databases:
    name: mobilitydb
    plan: free
    databaseName: mobility
    user: mobility

services:
  - type: web
    plan: free
    name: mobility
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mobility.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mobilitydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
