databases:
    name: mobility
    plan: free
    databaseName: mobility
    user: mobility_user

services:
  - type: web
    plan: free
    name: mobility
    runtime: python
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mobility.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mobility
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
